# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest  # Cambia aquí según tu preferencia

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

   - name: Change directory
      run: cd sesion5-integracion-continua

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
