# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest  # Cambia aquí según tu preferencia

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Ajusta la versión de Node.js según tus necesidades

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
       
          echo Add other actions to build,
          echo test, and deploy your project.
